#ifndef ENUMS_H
#define ENUMS_H

enum texture_id{NONE,BRICK,TILES,WOOD1,WOOD2,WOOD3,WOOD4,WALL1,WALL2,WALL3,WALL4,WALL5,TILE1,TILE2,WINDOW1,BEDSHEET1,
    BEDSHEET2,BEDSHEET3,BLANKET1,BLANKET2,PILLOW1,PILLOW2,PILLOW3,FIELD1,ROAD1,ROAD1_VER,
    ROAD_INT1,ROAD_INT2,FENCE1,TREE_BODY1,TREE_BODY2,TREE_BODY3,TREE_LEAF1,TREE_LEAF2,TREE_LEAF2_V2,TREE_LEAF2_V3,
    TREE_LEAF3,TREE_LEAF3_V2,TREE_LEAF4,TREE_LEAF4_V2,GRASS1,GRASS2,GRASS3,POND1,POND2,POND3,POND4,
    POND5,BLACKBOARD,CHAIR1,CHAIR2,CHAIR3,FLOOR1,MEME_RECT,ROAD2,SKY_1,SKY_2,SKY_3,SKY_4,SKY_5,SKY_6,SKY_4_V2,
    TABLE_CLOTH_1,TABLE_CLOTH_2,TABLE_CLOTH_3,TABLE_CLOTH_1_V2,FOOTBALL_FIELD_1,FOOTBALL_FIELD_1_LH,FOOTBALL_FIELD_1_RH,
    SCENE_1,ALMIRAH_1_FRONT,ALMIRAH_2,ALMIRAH_2_FRONT,ALMIRAH_3,ALMIRAH_3_FRONT,MIRROR_1,MIRROR_2,MIRROR_3,
    SUN_1,SUN_GLARE_1,SUN_GLARE_2,SUN_GLARE_3,MOON_1,SHIRT_CLOTH_1,SHIRT_CLOTH_2};

enum room_face{RF_FRONT,RF_LEFT,RF_BACK,RF_RIGHT};

#endif // ENUMS_H
